api:
  address: :443
  admin_ids: []
  client_id: ""
  client_secret: ""
  enable: false
  public_address: https://yuri.example.com
  tls:
    cert_file: /etc/cert/example.com/example.com.cer
    enable: true
    key_file: /etc/cert/example.com/example.com.key
database:
  dsn: file:yuri.db.sqlite3
discord:
  general_prefix: y!
  owner_id: ""
  right_role_names:
    blocked: YuriBlocked
    player: '@everyone'
  status_shuffle:
    delay: 10s
    status:
    - Yuri v.2!
    - zekro.de
    - github.com/zekroTJA/yuri2
  token: ""
lavalink:
  address: localhost:2333
  password: ""
  sounds_locations: []
misc:
  log_level: 4
